inworld-ai/inworld-nodejs-sdk

CHANGELOG.md
__tests__/factories/event.spec.ts
__tests__/services/inworld_connection.service.spec.ts
src/entities/inworld_packet.entity.ts
src/factories/event.ts
src/index.ts
src/services/inworld_connection.service.ts

`connection.sendTrigger('name', [{ name: 'p_name1', value: 'p_value1' }]);`

Add parameters to triggers

---

CHANGELOG.md
package.json
src/common/interfaces.ts

- Fix type definition for `onSession` method

Release 1.3.1

---

CHANGELOG.md
__tests__/clients/inworld.client.extension.spec.ts
__tests__/clients/inworld.client.spec.ts
__tests__/data_structures.ts
__tests__/factories/event.spec.ts
__tests__/helpers.ts
__tests__/services/connection.service.spec.ts
__tests__/services/grpc/world_engine_client_grpc.service.spec.ts
__tests__/services/inworld_connection.service.spec.ts
jest.config.json
package.json
src/auth/key_signature.ts
src/clients/inworld.client.ts
src/common/data_structures.ts
src/entities/inworld_packet.entity.ts
src/entities/session_token.entity.ts
src/factories/event.ts
src/index.ts
src/services/connection.service.ts
src/services/gprc/token_client_grpc.service.ts
src/services/gprc/world_engine_client_grpc.service.ts
src/services/inworld_connection.service.ts

* Replace CancelResponses by Mutation.CancelResponses on the protocol level
* Allow to use extended capabilities and scene props
* Allow to send and receive custom proto packet

Release 1.4.0

---

.gitignore
CHANGELOG.md
__tests__/clients/inworld.client.extension.spec.ts
__tests__/clients/inworld.client.spec.ts
__tests__/common/logger.spec.ts
__tests__/mocks/winston.mock.ts
__tests__/services/connection.service.spec.ts
__tests__/services/grpc/token_client_grpc.service.spec.ts
__tests__/services/grpc/world_engine_client_grpc.service.spec.ts
__tests__/services/inworld_connection.service.spec.ts
jest.config.json
package.json
src/clients/inworld.client.ts
src/common/logger.ts
src/services/connection.service.ts
src/services/gprc/token_client_grpc.service.ts
src/services/gprc/world_engine_client_grpc.service.ts
yarn.lock

Use env variables to enable logs:
NODE_SDK_INWORLD_LOGGER_ENABLED
NODE_SDK_INWORLD_LOGGER_FOLDER

Support debug mode

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/reviewdog.yml
.npmignore
.release-it.json
CHANGELOG.md
RELEASEME.md
package.json
yarn.lock

No need to change version in package.json and CHANGELOG.md during release publishing
It will be done automatically using Release & Publish to NPM GitHub action

Add release manual workflow

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/pull_request_template.md

The same as https://github.com/inworld-ai/inworld-web-sdk/pull/63

chore: Add issues and PR templates

---

.npmignore
EXTENSIONS.md

Add docs
https://inworldai.atlassian.net/browse/CORE-3851

feat: Add extensions doc

---

.github/actions/build_package/action.yml
.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/reviewdog.yml

Improve release process. I.e. splitting release wf to 3 steps:
- GitHub release + tag
- Npm release
- Slack notifications
So it'll be possible to restart `npm publish` step in case of failure
https://inworldai.atlassian.net/browse/CORE-3831

Slack notifications

---

.npmignore
TESTME.md

- Unit testing
- Manual testing
https://inworldai.atlassian.net/browse/CORE-4129

Add documentation detailing how to test the package

---

examples/js/cli/components/client.js
examples/js/cli/manual_reconnect.js
examples/ts/cli/components/client.ts
examples/ts/cli/manual_reconnect.ts

Add example to save and restore session
https://inworldai.atlassian.net/browse/CORE-3686

Previous state example for CLI

---

CHANGELOG.md
__tests__/entities/inworld_packet.entity.spec.ts
__tests__/factories/event.spec.ts
__tests__/helpers.ts
src/clients/inworld.client.ts
src/common/data_structures.ts
src/entities/inworld_packet.entity.ts

These feature is present in Web SDK, but it was missed in Node.js SDK
https://inworldai.atlassian.net/browse/CORE-4093

Narrated actions

---

examples/js/cli/components/client.js
examples/js/cli/components/player.js
examples/js/cli/package.json
examples/js/cli/yarn.lock
examples/ts/cli/components/client.ts
examples/ts/cli/components/player.ts
examples/ts/cli/package.json
examples/ts/cli/yarn.lock

It's impossible to kill child process on Windows in the regular way if process was created by fork command:
https://stackoverflow.com/questions/32705857/cant-kill-child-process-on-windows
https://inworldai.atlassian.net/browse/CORE-4132

fix: Fix child process killing on win32

---

CHANGELOG.md
LICENSE.md

Update LICENSE
https://inworldai.atlassian.net/browse/INTG-903

chore: Update LICENSE.md

---

.github/actions/build_package/action.yml
.github/workflows/build.yml

Working directory should be clean because it's required for Release action
https://inworldai.atlassian.net/browse/INTG-923

fix: Ensure working directory is clean

---

CHANGELOG.md
__tests__/factories/event.spec.ts
__tests__/services/inworld_connection.service.spec.ts
proto/ai/inworld/engine/world-engine_pb.d.ts
proto/ai/inworld/engine/world-engine_pb.js
proto/ai/inworld/language_codes/language_codes_pb.d.ts
proto/ai/inworld/language_codes/language_codes_pb.js
proto/ai/inworld/packets/packets_pb.d.ts
proto/ai/inworld/packets/packets_pb.js
src/factories/event.ts
src/services/inworld_connection.service.ts

Add new event: Outgoing narrated action
Incoming one is already supported
https://inworldai.atlassian.net/browse/INTG-876

feat: Outgoing narrated actions support

---

CHANGELOG.md

fix: Fix changelog

---

examples/js/cli/auto_reconnect.js
examples/js/cli/manual_reconnect.js
examples/js/cli/package.json
examples/js/cli/yarn.lock
examples/ts/cli/auto_reconnect.ts
examples/ts/cli/manual_reconnect.ts
examples/ts/cli/package.json
examples/ts/cli/yarn.lock

**!!! NEED TO PUBLISH PACKAGE AND CHANGE VERSION IN PACKAGE.JSON**
Add narrated actions to example
https://inworldai.atlassian.net/browse/INTG-876

feat: Add narrated action example

---

CHANGELOG.md
__tests__/entities/inworld_packet.entity.spec.ts
__tests__/entities/scene.entity.spec.ts
__tests__/factories/event.spec.ts
__tests__/services/connection.service.spec.ts
__tests__/services/grpc/world_engine_client_grpc.service.spec.ts
__tests__/services/inworld_connection.service.spec.ts
src/clients/inworld.client.ts
src/common/constants.ts
src/common/data_structures.ts
src/common/errors.ts
src/entities/character.entity.ts
src/entities/packets/inworld_packet.entity.ts
src/entities/scene.entity.ts
src/factories/event.ts
src/guard/scene.ts
src/services/connection.service.ts
src/services/gprc/world_engine_client_grpc.service.ts
src/services/inworld_connection.service.ts

- Need to move examples changes to separate PR after testing!!!
https://inworldai.atlassian.net/browse/INTG-1263

feat: Allow to change scene and add characters to current scene

---

.github/workflows/build.yml
.github/workflows/daily.yml
.github/workflows/demand.yml
e2e/e2e_helpers.ts
e2e/text/text.spec.ts
package.json

- Created E2E helper functions `sendText `and `sendAudio `for E2E tests
- Created a basic test spec `text.spec.ts` to test functions
- Created initial GHA workflow `daily` for daily runs and `demand` for on demand runs

E2E Helper Functions and Test GHA Workflows

---

examples/js/cli/auto_reconnect.js
examples/js/cli/components/conversation.js
examples/ts/cli/auto_reconnect.ts
examples/ts/cli/components/conversation.ts

Example for CLI
https://inworldai.atlassian.net/browse/INTG-446

example: Example for Feedback implementation

---

CHANGELOG.md
src/services/connection.service.ts

Forget to propagate onMessage callback to changeScene
https://inworldai.atlassian.net/browse/INTG-1728

fix: Fix scene changing error

---

examples/js/cli/package.json
examples/js/cli/yarn.lock
examples/js/generate_token/package.json
examples/js/generate_token/yarn.lock
examples/js/say_hello/package.json
examples/js/say_hello/yarn.lock
examples/js/upload_local_audio_file/package.json
examples/js/upload_local_audio_file/yarn.lock
examples/ts/cli/package.json
examples/ts/cli/yarn.lock
examples/ts/discord_bot/package.json
examples/ts/discord_bot/src/bot/inworld.connection.ts
examples/ts/discord_bot/src/bot/inworld.service.ts
examples/ts/discord_bot/yarn.lock
examples/ts/generate_token/package.json
examples/ts/generate_token/yarn.lock
examples/ts/say_hello/index.ts
examples/ts/say_hello/package.json
examples/ts/say_hello/yarn.lock
examples/ts/upload_local_audio_file/index.ts
examples/ts/upload_local_audio_file/package.json
examples/ts/upload_local_audio_file/yarn.lock

example: Bump SDK version

---

CHANGELOG.md
package.json

fix: Move @stackpath/node-grpc-error-details to main dependencies

---

.github/workflows/demand.yml

Demand test fix

---

examples/js/cli/package.json
examples/js/cli/yarn.lock
examples/js/generate_token/package.json
examples/js/generate_token/yarn.lock
examples/js/say_hello/package.json
examples/js/say_hello/yarn.lock
examples/js/upload_local_audio_file/package.json
examples/js/upload_local_audio_file/yarn.lock
examples/ts/cli/package.json
examples/ts/cli/yarn.lock
examples/ts/discord_bot/package.json
examples/ts/discord_bot/yarn.lock
examples/ts/generate_token/package.json
examples/ts/generate_token/yarn.lock
examples/ts/say_hello/package.json
examples/ts/say_hello/yarn.lock
examples/ts/upload_local_audio_file/package.json
examples/ts/upload_local_audio_file/yarn.lock

chore: Bump SDK package

---

__tests__/entities/error.entity.spec.ts
src/common/helpers.ts

fix: Fix path to google status proto

---

examples/js/cli/auto_reconnect.js
examples/ts/cli/auto_reconnect.ts

Reverts inworld-ai/inworld-nodejs-sdk#247

Revert "example: Support SPEECH_RECOGNITION_ONLY mode"

---

src/entities/continuation/session_continuation.entity.ts

https://inworldai.atlassian.net/browse/INTG-1928

feat: Allow to propagate previous state as Uint8Array to new connection

---

src/entities/continuation/session_continuation.entity.ts

https://inworldai.atlassian.net/browse/INTG-1928

fix: Add missed type

---

src/entities/entities/entity_item.ts

fix: Add default value for properties

---

examples/js/cli/auto_reconnect.js
examples/js/cli/manual_reconnect.js
examples/ts/cli/auto_reconnect.ts
examples/ts/cli/components/client.ts
examples/ts/cli/manual_reconnect.ts

https://inworldai.atlassian.net/browse/INTG-1851

example: Allow to changes scene from manual reconnect CLI example

---

.github/workflows/release.yml
.npmignore
.release-it.prerelease.json

https://inworldai.atlassian.net/browse/INTG-2025

chore: Allow to release custom beta version

---

.github/workflows/release.yml

fix: Fix config setup

---

.github/workflows/release.yml

fix: Fix typo

---

examples/js/cli/auto_reconnect.js
examples/js/cli/manual_reconnect.js
examples/js/cli/package.json
examples/js/cli/yarn.lock
examples/js/generate_token/package.json
examples/js/generate_token/yarn.lock
examples/js/say_hello/package.json
examples/js/say_hello/yarn.lock
examples/js/upload_local_audio_file/package.json
examples/js/upload_local_audio_file/yarn.lock
examples/ts/cli/auto_reconnect.ts
examples/ts/cli/components/client.ts
examples/ts/cli/components/types.ts
examples/ts/cli/helpers.ts
examples/ts/cli/manual_reconnect.ts
examples/ts/cli/map.ts
examples/ts/cli/package.json
examples/ts/cli/yarn.lock
examples/ts/discord_bot/package.json
examples/ts/discord_bot/yarn.lock
examples/ts/generate_token/package.json
examples/ts/generate_token/yarn.lock
examples/ts/say_hello/package.json
examples/ts/say_hello/yarn.lock
examples/ts/upload_local_audio_file/package.json
examples/ts/upload_local_audio_file/yarn.lock

https://inworldai.atlassian.net/projects/INTG/versions/10061/tab/release-report-all-issues

Examples for 1.15

---

RELEASEME.md

docs: Update RELEASEME.md

---

__tests__/common/helpers.spec.ts
__tests__/entities/entities/item_operation.spec.ts
__tests__/entities/task.entity.spec.ts
__tests__/services/conversation.service.spec.ts
__tests__/services/grpc/world_engine_client_grpc.service.spec.ts
__tests__/services/inworld_connection.service.spec.ts
src/entities/entities/item_operation.ts
src/entities/error.entity.ts
src/entities/packets/inworld_packet.entity.ts
src/services/inworld_connection.service.ts

https://inworldai.atlassian.net/browse/INTG-2026

chore: Improve test coverage

---

src/common/data_structures.ts
src/entities/capability.entity.ts
src/entities/packets/log.entity.ts

feat: Add Internal logs support

---

CHANGELOG.md
package.json
src/common/data_structures.ts
src/services/inworld_connection.service.ts

fix: Wait for one-to-one conversation loading on data sending

---

CHANGELOG.md
examples/ts/cli/components/client.ts
src/common/data_structures.ts
src/entities/packets/log.entity.ts
src/index.ts

https://inworldai.atlassian.net/browse/INTG-2213

feat: Add details to logs

---

.release-it.json

https://inworldai.atlassian.net/browse/INTG-2220

chore: Make CHANGELOG version validation to be optional during release action

---

CHANGELOG.md
__tests__/entities/entities/capability.entity.spec.ts
__tests__/entities/packets/emotion/emotion_behavior.entity.spec.ts
__tests__/entities/packets/emotion/emotion_strength.entity.spec.ts
__tests__/entities/packets/inworld_packet.entity.spec.ts
__tests__/entities/packets/task.entity.spec.ts
__tests__/services/connection.service.spec.ts
__tests__/services/conversation.service.spec.ts
__tests__/services/inworld_connection.service.spec.ts
examples/js/cli/auto_reconnect.js
examples/js/cli/interruptions.js
examples/js/cli/manual_reconnect.js
examples/js/cli/multi_characters.js
examples/ts/cli/auto_reconnect.ts
examples/ts/cli/interruptions.ts
examples/ts/cli/manual_reconnect.ts
examples/ts/cli/map.ts
examples/ts/cli/multi_characters.ts
src/clients/inworld.client.ts
src/entities/capability.entity.ts
src/entities/packets/latency/ping_pong_report.entity.ts
src/services/connection.service.ts
src/services/gprc/world_engine_client_grpc.service.ts
src/services/inworld_connection.service.ts

https://inworldai.atlassian.net/browse/INTG-2327

fix: Fix changing of scene capabilities

---

src/index.ts

[](https://inworldai.atlassian.net/browse/INTG-2398)

chore: Change 2024 to 2025 in copyright terms
